function devhttpclient(){var N='bootstrap',O='begin',P='gwt.codesvr.devhttpclient=',Q='gwt.codesvr=',R='devhttpclient',S='startup',T='DUMMY',U=0,V=1,W='undefined',X='readystatechange',Y=10,Z='script',$='javascript',_='Failed to load ',ab='moduleStartup',bb='scriptTagAdded',cb='moduleRequested',db='meta',eb='name',fb='devhttpclient::',gb='',hb='::',ib='gwt:property',jb='content',kb='=',lb='gwt:onPropertyErrorFn',mb='Bad handler "',nb='" for "gwt:onPropertyErrorFn"',ob='gwt:onLoadErrorFn',pb='" for "gwt:onLoadErrorFn"',qb='#',rb='?',sb='/',tb='img',ub='clear.cache.gif',vb='baseUrl',wb='devhttpclient.nocache.js',xb='base',yb='//',zb='selectingPermutation',Ab='devhttpclient.devmode.js',Bb='838272275A7669E5EA06933AEC7C9C6E',Cb=':',Db='.cache.js',Eb='loadExternalRefs',Fb='end',Gb='http:',Hb='file:',Ib='_gwt_dummy_',Jb='__gwtDevModeHook:devhttpclient',Kb='Ignoring non-whitelisted Dev Mode URL: ',Lb=':moduleBase',Mb='head';var n=window;var o=document;q(N,O);function p(){var a=n.location.search;return a.indexOf(P)!=-1||a.indexOf(Q)!=-1}
function q(a,b){if(n.__gwtStatsEvent){n.__gwtStatsEvent({moduleName:R,sessionId:n.__gwtStatsSessionId,subSystem:S,evtGroup:a,millis:(new Date).getTime(),type:b})}}
devhttpclient.__sendStats=q;devhttpclient.__moduleName=R;devhttpclient.__errFn=null;devhttpclient.__moduleBase=T;devhttpclient.__softPermutationId=U;devhttpclient.__computePropValue=null;devhttpclient.__getPropMap=null;devhttpclient.__installRunAsyncCode=function(){};devhttpclient.__gwtStartLoadingFragment=function(){return null};devhttpclient.__gwt_isKnownPropertyValue=function(){return false};devhttpclient.__gwt_getMetaProperty=function(){return null};var r=null;var s=n.__gwt_activeModules=n.__gwt_activeModules||{};s[R]={moduleName:R};devhttpclient.__moduleStartupDone=function(e){var f=s[R].bindings;s[R].bindings=function(){var a=f?f():{};var b=e[devhttpclient.__softPermutationId];for(var c=U;c<b.length;c++){var d=b[c];a[d[U]]=d[V]}return a}};var t;function u(){v();return t}
function v(){if(t){return}t=n.document;if(!t){t=n.document}}
function w(f){function g(a){function b(){if(typeof o.readyState==W){return typeof o.body!=W&&o.body!=null}return /loaded|complete/.test(o.readyState)}
var c=b();if(c){a();return}function d(){if(!c){if(!b()){return}c=true;a();if(o.removeEventListener){o.removeEventListener(X,d,false)}if(e){clearInterval(e)}}}
if(o.addEventListener){o.addEventListener(X,d,false)}var e=setInterval(function(){d()},Y)}
function h(a){var b=u();var c=b.body;var d=b.createElement(Z);d.language=$;d.src=a;if(devhttpclient.__errFn){d.onerror=function(){devhttpclient.__errFn(R,new Error(_+a))}}c.appendChild(d);q(ab,bb)}
q(ab,cb);g(function(){h(f)})}
devhttpclient.__startLoadingFragment=function(a){return C(a)};devhttpclient.__installRunAsyncCode=function(a){var b=u();var c=b.body;var d=b.createElement(Z);d.language=$;d.text=a;c.appendChild(d);c.removeChild(d)};function A(){var c={};var d;var e;var f=o.getElementsByTagName(db);for(var g=U,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(eb),k;if(j){j=j.replace(fb,gb);if(j.indexOf(hb)>=U){continue}if(j==ib){k=i.getAttribute(jb);if(k){var l,m=k.indexOf(kb);if(m>=U){j=k.substring(U,m);l=k.substring(m+V)}else{j=k;l=gb}c[j]=l}}else if(j==lb){k=i.getAttribute(jb);if(k){try{d=eval(k)}catch(a){alert(mb+k+nb)}}}else if(j==ob){k=i.getAttribute(jb);if(k){try{e=eval(k)}catch(a){alert(mb+k+pb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};r=d;devhttpclient.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(qb);if(b==-1){b=a.length}var c=a.indexOf(rb);if(c==-1){c=a.length}var d=a.lastIndexOf(sb,Math.min(c,b));return d>=U?a.substring(U,d+V):gb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=o.createElement(tb);b.src=a+ub;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(vb);if(a!=null){return a}return gb}
function h(){var a=o.getElementsByTagName(Z);for(var b=U;b<a.length;++b){if(a[b].src.indexOf(wb)!=-1){return e(a[b].src)}}return gb}
function i(){var a=o.getElementsByTagName(xb);if(a.length>U){return a[a.length-V].href}return gb}
function j(){var a=o.location;return a.href==a.protocol+yb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==gb){k=h()}if(k==gb){k=i()}if(k==gb&&j()){k=e(o.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return devhttpclient.__moduleBase+a}
function D(){var f=[];var g=U;var h=[];var i=[];function j(a){var b=i[a](),c=h[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(r){r(a,d,b)}throw null}
__gwt_isKnownPropertyValue=function(a,b){return b in h[a]};devhttpclient.__getPropMap=function(){var a={};for(var b in h){if(h.hasOwnProperty(b)){a[b]=j(b)}}return a};devhttpclient.__computePropValue=j;n.__gwt_activeModules[R].bindings=devhttpclient.__getPropMap;q(N,zb);if(p()){return C(Ab)}var k;try{k=Bb;var l=k.indexOf(Cb);if(l!=-1){g=parseInt(k.substring(l+V),Y);k=k.substring(U,l)}}catch(a){}devhttpclient.__softPermutationId=g;return C(k+Db)}
function F(){if(!n.__gwt_stylesLoaded){n.__gwt_stylesLoaded={}}q(Eb,O);q(Eb,Fb)}
A();devhttpclient.__moduleBase=B();s[R].moduleBase=devhttpclient.__moduleBase;var G=D();if(n){var H=!!(n.location.protocol==Gb||n.location.protocol==Hb);n.__gwt_activeModules[R].canRedirect=H;function I(){var b=Ib;try{n.sessionStorage.setItem(b,b);n.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(H&&I()){var J=Jb;var K=n.sessionStorage[J];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(K)){if(K&&(window.console&&console.log)){console.log(Kb+K)}K=gb}if(K&&!n[J]){n[J]=true;n[J+Lb]=B();var L=o.createElement(Z);L.src=K;var M=o.getElementsByTagName(Mb)[U];M.insertBefore(L,M.firstElementChild||M.children[U]);return false}}}F();q(N,Fb);w(G);return true}
devhttpclient.succeeded=devhttpclient();